# Generated by Django 5.1.1 on 2025-07-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mherouser',
            name='profile_photo',
        ),
    ]
