# Generated by Django 5.1.1 on 2025-07-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_mherouser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mherouser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
