# Generated by Django 5.1.1 on 2025-07-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mherouser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mherouser',
            name='company',
        ),
    ]
